[server]
   enableStaticServing = true
[theme]
base = "light"
[theme]
font = "Inter Tight:https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;500;600;700&display=swap"
headingFont = "Inter Tight:https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;500;600;700&display=swap"
